"use client";

import { useState } from "react";
import { AdminPageHeader, AdminShell } from "@/components/admin";
import { mockOrders } from "@/lib/data";
import { StatusBadge, Toast } from "@/components/site";

type Filter = "All" | "Processing" | "Delivered";
const timeline = ["Order placed", "Processing", "Preparing", "Dispatched", "Delivered"];

export default function AdminOrdersPage() {
  const [selected, setSelected] = useState<string | null>(null);
  const [filter, setFilter] = useState<Filter>("All");
  const [toast, setToast] = useState("");
  const order = mockOrders.find((item) => item.id === selected);
  const visibleOrders = mockOrders.filter((item) => filter === "All" || (filter === "Processing" ? item.status !== "Entregado" : item.status === "Entregado"));
  return <AdminShell><AdminPageHeader eyebrow="COMMERCE" title="Orders" body="Review orders, filter their delivery status, and see each order timeline." action={<button onClick={() => setToast("CSV export is ready for the backend connection")} className="rounded-full border border-[#dfe3eb] bg-white px-4 py-3 text-xs font-black">Export CSV</button>} />
    <section className="mt-8 overflow-hidden rounded-2xl border border-[#e4e7ee] bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#e4e7ee] p-5"><p className="text-sm font-black">{visibleOrders.length} shown · 1,284 total orders</p><div className="flex gap-2">{(["All", "Processing", "Delivered"] as Filter[]).map((item) => <button key={item} onClick={() => setFilter(item)} className={`rounded-full px-3 py-2 text-[11px] font-black ${filter === item ? "bg-[#182443] text-white" : "border border-[#dfd3cc]"}`}>{item}</button>)}</div></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b border-[#e4e7ee] bg-[#fafbfc] text-[10px] uppercase tracking-[.14em] text-[#9297a4]"><th className="px-5 py-3 font-black">Order</th><th className="px-5 py-3 font-black">Date</th><th className="px-5 py-3 font-black">Product</th><th className="px-5 py-3 font-black">Amount</th><th className="px-5 py-3 font-black">Payment</th><th className="px-5 py-3 font-black">Status</th><th className="px-5 py-3" /></tr></thead><tbody>{visibleOrders.map((item) => <tr key={item.id} className="border-b border-[#eef0f4] text-sm last:border-0"><td className="px-5 py-4 font-black">{item.id}</td><td className="px-5 py-4 text-[#737b90]">{item.date}</td><td className="px-5 py-4 font-bold">{item.item || "Personalised card"}</td><td className="px-5 py-4 font-black">{item.amount}</td><td className="px-5 py-4"><StatusBadge tone="green">{item.payment}</StatusBadge></td><td className="px-5 py-4"><StatusBadge tone={item.statusTone as "green" | "amber"}>{item.status}</StatusBadge></td><td className="px-5 py-4"><button onClick={() => setSelected(item.id)} className="text-xs font-black text-[#ee5264]">Details</button></td></tr>)}</tbody></table></div></section>
    {order && <div className="fixed inset-0 z-50"><button className="absolute inset-0 bg-[#182443]/25" onClick={() => setSelected(null)} aria-label="Close details" /><aside className="absolute bottom-0 right-0 top-0 w-full max-w-[410px] overflow-y-auto bg-white p-6 shadow-2xl sm:p-8"><button onClick={() => setSelected(null)} className="float-right text-xs font-black text-[#737b90]">Close</button><p className="pt-8 text-[10px] font-black tracking-widest text-[#ee5264]">ORDER DETAIL</p><h2 className="mt-2 text-2xl font-black">{order.id}</h2><p className="mt-2 text-sm text-[#737b90]">{order.item || "Personalised card"} · {order.amount} · {order.delivery}</p><div className="mt-10 space-y-0">{timeline.map((step, index) => <div key={step} className="flex gap-4"><div className="flex flex-col items-center"><span className={`flex h-7 w-7 items-center justify-center rounded-full text-xs font-black ${index < (order.status === "Entregado" ? 5 : 4) ? "bg-[#182443] text-white" : "bg-[#eef0f4] text-[#9297a4]"}`}>{index < (order.status === "Entregado" ? 5 : 4) ? "✓" : index + 1}</span>{index < 4 && <span className="h-10 w-px bg-[#dfe3eb]" />}</div><div className="pt-1"><p className="text-sm font-black">{step}</p><p className="mt-1 text-xs text-[#9297a4]">{index < (order.status === "Entregado" ? 5 : 4) ? "Complete" : "Awaiting update"}</p></div></div>)}</div></aside></div>}{toast && <Toast message={toast} onClose={() => setToast("")} />}
  </AdminShell>;
}
