"use client";

import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { Icon } from "@/components/icons";
import { PageIntro, SiteFooter, SiteHeader } from "@/components/site";

const contactSchema = z.object({ name: z.string().min(2, "Escribe tu nombre"), email: z.string().email("Introduce un email válido"), subject: z.string().min(3, "Añade un asunto"), message: z.string().min(10, "Cuéntanos un poco más") });
type ContactForm = z.infer<typeof contactSchema>;

export default function ContactPage() { const [sent, setSent] = useState(false); const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<ContactForm>({ resolver: zodResolver(contactSchema) }); if (sent) return <><SiteHeader /><main className="flex min-h-[60vh] items-center justify-center bg-[#fffaf5] px-5 py-20"><div className="max-w-[500px] text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-[#e8f5ed] text-[#24714b]"><Icon name="check" size={28} /></div><h1 className="serif mt-6 text-5xl font-bold">Mensaje recibido.</h1><p className="mt-4 text-sm leading-7 text-[#737b90]">Gracias por escribirnos. Te responderemos con cariño lo antes posible.</p><button onClick={() => setSent(false)} className="mt-7 rounded-full bg-[#182443] px-5 py-3 text-sm font-black text-white">Enviar otro mensaje</button></div></main><SiteFooter /></>; return <><SiteHeader active="Ayuda" /><main className="bg-[#fffaf5] py-16 md:py-24"><div className="container"><PageIntro eyebrow="ESTAMOS PARA AYUDARTE" title="Hablemos" body="¿Tienes una pregunta sobre tu tarjeta, un pedido o una idea especial? Escríbenos." /><div className="mx-auto mt-12 grid max-w-[930px] gap-7 md:grid-cols-[.72fr_1.28fr]"><aside className="rounded-[24px] bg-[#182443] p-6 text-white sm:p-8"><h2 className="text-xl font-black">Estamos cerca</h2><p className="mt-3 text-sm leading-6 text-white/65">Nuestro equipo responde de lunes a viernes, de 9:00 a 18:00.</p><div className="mt-10 space-y-5 text-sm"><div><p className="text-[10px] font-black uppercase tracking-[.15em] text-[#f8c75e]">Email</p><p className="mt-2 font-bold">hola@celebramomentos.com</p></div><div><p className="text-[10px] font-black uppercase tracking-[.15em] text-[#f8c75e]">Ayuda con pedidos</p><p className="mt-2 font-bold">Incluye tu número CM- en el mensaje.</p></div></div></aside><form onSubmit={handleSubmit(() => setSent(true))} className="rounded-[24px] border border-[#eadbd3] bg-white p-6 sm:p-8"><div className="grid gap-4 sm:grid-cols-2"><Field label="Nombre" error={errors.name?.message}><input {...register("name")} className="field" placeholder="María García" /></Field><Field label="Email" error={errors.email?.message}><input {...register("email")} className="field" placeholder="hola@ejemplo.com" /></Field></div><Field label="Asunto" error={errors.subject?.message}><input {...register("subject")} className="field" placeholder="Tengo una duda sobre mi pedido" /></Field><Field label="Mensaje" error={errors.message?.message}><textarea {...register("message")} rows={5} className="field resize-none" placeholder="Cuéntanos cómo podemos ayudarte…" /></Field><button disabled={isSubmitting} className="focus-ring mt-5 inline-flex items-center gap-2 rounded-full bg-[#ee5264] px-5 py-3.5 text-sm font-black text-white hover:bg-[#d83d54] disabled:opacity-60">Enviar mensaje <Icon name="arrow" size={16} /></button></form></div></div></main><SiteFooter /></>; }
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="mt-4 block text-sm font-black first:mt-0">{label}{children}{error && <span className="mt-1 block text-xs font-bold text-[#c94758]">{error}</span>}</label>; }
