"use client";

import { useState } from "react";
import { AdminPageHeader, AdminShell } from "@/components/admin";
import { Icon } from "@/components/icons";
import { addOns, templates } from "@/lib/data";
import { Price, StatusBadge, Toast } from "@/components/site";

export default function AdminProductsPage() { const products = [...templates.map((item) => ({ id: item.id, name: item.name, category: "Postcard template", price: item.price })), ...addOns.map((item) => ({ id: item.id, name: item.name, category: "Custom sticker", price: item.price }))]; const [active, setActive] = useState<Record<string, boolean>>(() => Object.fromEntries(products.map((item) => [item.id, true]))); const [toast, setToast] = useState(""); return <AdminShell><AdminPageHeader eyebrow="CATALOG" title="Products" body="Manage the products customers can add to their moment." action={<button onClick={() => setToast("Product creation is ready for API connection")} className="rounded-full bg-[#ee5264] px-4 py-3 text-xs font-black text-white hover:bg-[#d83d54]">+ Add product</button>} /><section className="mt-8 overflow-hidden rounded-2xl border border-[#e4e7ee] bg-white"><div className="flex items-center justify-between border-b border-[#e4e7ee] p-5"><p className="text-sm font-black">{products.length} products</p><span className="text-xs text-[#9297a4]">Mock catalog</span></div><div className="overflow-x-auto"><table className="w-full min-w-[690px] text-left"><thead><tr className="border-b border-[#e4e7ee] bg-[#fafbfc] text-[10px] uppercase tracking-[.14em] text-[#9297a4]"><th className="px-5 py-3 font-black">Product</th><th className="px-5 py-3 font-black">Category</th><th className="px-5 py-3 font-black">Price</th><th className="px-5 py-3 font-black">Status</th><th className="px-5 py-3 font-black text-right">Actions</th></tr></thead><tbody>{products.map((product) => <tr key={product.id} className="border-b border-[#eef0f4] text-sm last:border-0"><td className="px-5 py-4 font-black">{product.name}</td><td className="px-5 py-4 text-[#737b90]">{product.category}</td><td className="px-5 py-4 font-black"><Price value={product.price} /></td><td className="px-5 py-4"><button onClick={() => { setActive((current) => ({ ...current, [product.id]: !current[product.id] })); setToast(`${product.name} ${active[product.id] ? "deactivated" : "activated"}`); }}><StatusBadge tone={active[product.id] ? "green" : "slate"}>{active[product.id] ? "Active" : "Inactive"}</StatusBadge></button></td><td className="px-5 py-4 text-right"><button onClick={() => setToast(`Edit form opened for ${product.name}`)} className="inline-flex items-center gap-2 rounded-full border border-[#dfd3cc] px-3 py-2 text-xs font-black hover:border-[#ee5264]"><Icon name="edit" size={14} /> Edit</button></td></tr>)}</tbody></table></div></section>{toast && <Toast message={toast} onClose={() => setToast("")} />}</AdminShell>; }
