"use client";

import Link from "next/link";
import { useSelector } from "react-redux";
import { Icon } from "@/components/icons";
import { CardPreview } from "@/components/card-preview";
import { SiteFooter, SiteHeader } from "@/components/site";
import { RootState } from "@/lib/store";

type Category = { name: string; description: string; href: string; image: string; accent: string; price: string; position?: string };

const reviews = [
  { quote: "La tarjeta quedó incluso mejor de lo que imaginaba. Fue un regalo de verdad.", name: "María G.", detail: "Tarjeta personalizada" },
  { quote: "O calendário ficou lindo e criar cada página foi muito simples.", name: "João P.", detail: "Calendário A4" },
  { quote: "Ahora nuestras fotos favoritas forman parte de casa, no solo del móvil.", name: "Lucía R.", detail: "Arte de pared" },
];

export default function Home() {
  const language = useSelector((state: RootState) => state.language.language);
  const es = language === "es";
  const categories: Category[] = [
    { name: es ? "Tarjetas" : "Cartões", description: es ? "Añade fotos y tu propio mensaje" : "Adiciona fotografias e a tua mensagem", href: "/templates", image: "/images/birthday-celebration.png", accent: "bg-[#fbe7e1]", price: "8,90 €" },
    { name: es ? "Arte de pared" : "Arte de parede", description: es ? "Convierte recuerdos en algo precioso" : "Transforma memórias em algo bonito", href: "/wall-art", image: "/images/wall-art-product.png", accent: "bg-[#e7f1eb]", price: "29,90 €" },
    { name: es ? "Imanes" : "Ímanes", description: es ? "Pequeños recuerdos para tu nevera" : "Pequenas memórias para o frigorífico", href: "/magnets", image: "/images/magnets-product.png", accent: "bg-[#e8e7f6]", price: "9,90 €" },
    { name: es ? "Calendarios" : "Calendários", description: es ? "Un año con tus fotos favoritas" : "Um ano com as tuas fotografias favoritas", href: "/calendars", image: "/images/calendar-product.png", accent: "bg-[#fff1c7]", price: "16,90 €" },
    { name: es ? "Funda de móvil personalizada" : "Capa de telemóvel personalizada", description: es ? "Lleva tus mejores momentos contigo" : "Leva os teus melhores momentos contigo", href: "/phone-cases", image: "/images/personalised-phone-cases.png", accent: "bg-[#f4e8df]", price: "19,90 €" },
  ];
  const moments = [
    ["❤️", es ? "Cumpleaños" : "Aniversários", es ? "Una tarjeta o regalo que sí guardarán." : "Um cartão ou presente que vão guardar."],
    ["👨‍👩‍👧", es ? "Recuerdos familiares" : "Memórias de família", es ? "Tus personas favoritas, siempre cerca." : "As tuas pessoas favoritas, sempre por perto."],
    ["💍", es ? "Aniversarios" : "Datas especiais", es ? "Celebra vuestra historia a vuestra manera." : "Celebra a vossa história à vossa maneira."],
    ["🎄", es ? "Navidad y celebraciones" : "Natal e celebrações", es ? "Regalos hechos con los recuerdos que amas." : "Presentes feitos com as memórias que amas."],
    ["🏡", es ? "Para tu hogar" : "Para a tua casa", es ? "Llena tus paredes de vida y significado." : "Enche as tuas paredes de vida e significado."],
  ];

  return <>
    <SiteHeader />
    <main>
      <section id="top" className="relative overflow-hidden border-b border-[#ebdfd6] bg-[#fffaf5]">
        <div className="absolute -left-24 bottom-0 h-72 w-72 rounded-full bg-[#ee5264]/10 blur-3xl" />
        <div className="container grid items-center gap-12 py-14 md:py-20 lg:grid-cols-[.88fr_1.12fr] lg:gap-16 lg:py-24">
          <div className="relative z-10 max-w-[570px]">
            <p className="mb-5 text-[10px] font-black uppercase tracking-[.2em] text-[#ee5264]">{es ? "TUS RECUERDOS, HECHOS REGALO" : "AS TUAS MEMÓRIAS, FEITAS PRESENTE"}</p>
            <h1 className="serif text-[51px] font-bold leading-[.96] tracking-[-.055em] text-[#182443] sm:text-[68px] lg:text-[76px]">{es ? <>Hazlo personal.<br /><span className="text-[#ee5264]">Hazlo tuyo.</span></> : <>Torna-o pessoal.<br /><span className="text-[#ee5264]">Torna-o teu.</span></>}</h1>
            <p className="mt-7 max-w-[520px] text-base leading-7 text-[#68718a]">{es ? "Convierte tus fotos favoritas y palabras especiales en regalos personalizados, recuerdos y cosas bonitas para tu hogar." : "Transforma as tuas fotografias favoritas e palavras especiais em presentes personalizados, recordações e coisas bonitas para a tua casa."}</p>
            <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/templates" className="focus-ring inline-flex items-center justify-center gap-3 rounded-full bg-[#ee5264] px-6 py-3.5 text-sm font-black text-white shadow-lg shadow-[#ee5264]/20 transition hover:-translate-y-0.5 hover:bg-[#d83d54]">{es ? "Crea el tuyo" : "Cria o teu"}<Icon name="arrow" size={17} /></Link><a href="#categories" className="focus-ring inline-flex items-center justify-center rounded-full border border-[#d9cbc4] bg-white px-6 py-3.5 text-sm font-black text-[#182443] transition hover:border-[#ee5264]">{es ? "Ver todos los productos" : "Ver todos os produtos"}</a></div>
            <p className="mt-7 flex flex-wrap items-center gap-x-2 gap-y-1 text-xs font-bold text-[#737b90]"><span>📸 {es ? "Sube tu foto" : "Carrega a fotografia"}</span><span>•</span><span>✍️ {es ? "Añade tu mensaje" : "Adiciona a mensagem"}</span><span>•</span><span>❤️ {es ? "Crea algo único" : "Cria algo único"}</span></p>
          </div>
          <div className="relative"><div className="absolute -inset-5 rotate-2 rounded-[34px] bg-[#f4d4c7]" /><div className="relative overflow-hidden rounded-[28px] border-[10px] border-white shadow-2xl shadow-[#8a564c]/20"><img src="/images/home-personalised-gifts.png" alt={es ? "Tarjeta, cuadro, calendario, funda e imanes personalizados" : "Cartão, quadro, calendário, capa e ímanes personalizados"} className="aspect-[3/2] h-full w-full object-cover" /></div><div className="float absolute -bottom-5 -left-3 rounded-2xl bg-white px-4 py-3 card-shadow sm:left-6"><p className="text-[10px] font-black uppercase tracking-wider text-[#ee5264]">{es ? "CREADO POR TI" : "CRIADO POR TI"}</p><p className="mt-1 text-sm font-black">{es ? "Único, como ellos" : "Único, como eles"} ❤️</p></div></div>
        </div>
      </section>

      <section id="categories" className="scroll-mt-28 bg-white py-16 md:py-24"><div className="container"><SectionHeading eyebrow={es ? "¿QUÉ PUEDES CREAR?" : "O QUE PODES CRIAR?"} title={es ? "Tus fotos pueden convertirse en mucho más" : "As tuas fotografias podem tornar-se muito mais"} body={es ? "Elige una idea. Después añade tus recuerdos y hazla completamente tuya." : "Escolhe uma ideia. Depois adiciona as tuas memórias e torna-a completamente tua."} /><div className="mt-11 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{categories.map((category) => <Link key={category.href} href={category.href} className="group focus-ring overflow-hidden rounded-[24px] border border-[#eadbd3] bg-[#fffaf5] transition duration-300 hover:-translate-y-1.5 hover:border-[#e9aaa0] hover:shadow-xl hover:shadow-[#8a564c]/10"><div className={`aspect-[1.05/1] overflow-hidden ${category.accent}`}><img src={category.image} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105" style={{ objectPosition: category.position }} /></div><div className="p-5"><div className="flex items-start justify-between gap-3"><h3 className="text-base font-black">{category.name}</h3><span className="whitespace-nowrap text-xs font-black text-[#ee5264]">{category.price}</span></div><p className="mt-2 min-h-[42px] text-xs leading-5 text-[#737b90]">{category.description}</p><span className="mt-4 inline-flex items-center gap-2 text-xs font-black text-[#ee5264]">Personalizar<Icon name="arrow" size={14} /></span></div></Link>)}</div></div></section>

      <section id="how" className="scroll-mt-28 border-y border-[#ebdfd6] bg-[#fff7f1] py-16 md:py-20"><div className="container"><SectionHeading eyebrow={es ? "ASÍ DE FÁCIL" : "É ASSIM TÃO FÁCIL"} title={es ? "Crea algo personal en 3 pasos" : "Cria algo pessoal em 3 passos"} body={es ? "Tú pones los recuerdos. Nosotros hacemos que el proceso sea sencillo." : "Tu trazes as memórias. Nós tornamos o processo simples."} /><ol className="mt-10 grid gap-4 md:grid-cols-3">{[
        ["01", es ? "Elige tu producto" : "Escolhe o produto", es ? "Empieza por una tarjeta, arte de pared, imanes, calendario o funda." : "Começa por um cartão, arte de parede, ímanes, calendário ou capa."],
        ["02", es ? "Añade fotos y palabras" : "Adiciona fotos e palavras", es ? "Sube tus imágenes favoritas y escribe tu propio mensaje." : "Carrega as imagens favoritas e escreve a tua mensagem."],
        ["03", es ? "Previsualiza y pide" : "Vê e encomenda", es ? "Comprueba tu creación y nosotros nos encargamos del resto." : "Confere a tua criação e nós tratamos do resto."],
      ].map(([number, title, body]) => <li key={number} className="rounded-[24px] border border-[#eadbd3] bg-white p-6"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-[#fff0e8] text-xs font-black text-[#ee5264]">{number}</span><h3 className="mt-5 text-lg font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-[#737b90]">{body}</p></li>)}</ol><div className="mx-auto mt-8 flex max-w-[830px] flex-wrap items-center justify-center gap-2 rounded-full border border-[#eadbd3] bg-white px-5 py-3 text-[10px] font-black uppercase tracking-[.12em] text-[#59627b]">{(es ? ["Elige", "Sube", "Personaliza", "Previsualiza", "Pide"] : ["Escolhe", "Carrega", "Personaliza", "Pré-visualiza", "Encomenda"]).map((label, index, all) => <span key={label} className="flex items-center gap-2"><span>{label}</span>{index < all.length - 1 && <span className="text-[#ee5264]">→</span>}</span>)}</div></div></section>

      <section id="moments" className="bg-white py-16 md:py-24"><div className="container"><SectionHeading eyebrow={es ? "HECHO PARA EMOCIONAR" : "FEITO PARA EMOCIONAR"} title={es ? "Para los momentos que importan" : "Para os momentos que importam"} body={es ? "No es solo lo que regalas. Es todo lo que ese recuerdo significa." : "Não é apenas o que ofereces. É tudo o que essa memória significa."} /><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{moments.map(([emoji, title, body]) => <article key={title} className="rounded-[22px] border border-[#eadbd3] bg-[#fffaf5] p-5"><span className="text-2xl">{emoji}</span><h3 className="mt-4 text-sm font-black">{title}</h3><p className="mt-2 text-xs leading-5 text-[#737b90]">{body}</p></article>)}</div></div></section>

      <section id="story" className="border-y border-[#ebdfd6] bg-[#182443] py-16 text-white md:py-24"><div className="container"><SectionHeading dark eyebrow={es ? "TU FOTO. TUS PALABRAS. TU HISTORIA." : "A TUA FOTO. AS TUAS PALAVRAS. A TUA HISTÓRIA."} title={es ? "Mira cómo un recuerdo cobra vida" : "Vê como uma memória ganha vida"} body={es ? "Cada creación empieza con algo que ya es importante para ti." : "Cada criação começa com algo que já é importante para ti."} /><div className="mt-12 grid gap-6 lg:grid-cols-2"><Transformation before="/images/sticker-family.jpg" after="/images/wall-art-product.png" label={es ? "Tu foto → arte de pared personalizada" : "A tua foto → arte de parede personalizada"} /><Transformation before="/images/birthday-celebration.png" after="/images/birthday-celebration.png" birthdayCard label={es ? "Tu foto + tu mensaje → una tarjeta única" : "A tua foto + a tua mensagem → um cartão único"} /></div></div></section>

      <section id="made-by-you" className="bg-[#fffaf5] py-16 md:py-24"><div className="container"><SectionHeading eyebrow={es ? "HECHO POR VOSOTROS" : "FEITO POR VOCÊS"} title={es ? "Creaciones de personas como tú" : "Criações de pessoas como tu"} body={es ? "Ideas reales para cumpleaños, bodas, aniversarios y días que merecen quedarse." : "Ideias reais para aniversários, casamentos e dias que merecem ficar."} /><div className="mx-auto mt-10 grid max-w-[870px] grid-cols-2 gap-3 md:grid-cols-3 md:grid-rows-2"><GalleryTile image="/images/sticker-family.jpg" className="md:row-span-2" label={es ? "Recuerdos familiares" : "Memórias de família"} /><GalleryTile image="/images/calendar-product.png" label={es ? "Calendarios" : "Calendários"} /><GalleryTile image="/images/magnets-product.png" label={es ? "Imanes" : "Ímanes"} /><GalleryTile image="/images/wall-art-product.png" className="col-span-2" label={es ? "Arte para el hogar" : "Arte para a casa"} /></div><p className="mt-7 text-center text-sm font-black">{es ? "Comparte tu creación" : "Partilha a tua criação"} <span className="text-[#ee5264]">#CelebraMomentos</span></p></div></section>

      <section id="reviews" className="bg-[#fff7f1] py-16 md:py-24"><div className="container"><SectionHeading eyebrow={es ? "HISTORIAS REALES" : "HISTÓRIAS REAIS"} title={es ? "Pequeños detalles. Grandes reacciones." : "Pequenos detalhes. Grandes reações."} /><div className="mt-10 grid gap-4 md:grid-cols-3">{reviews.map((review) => <figure key={review.name} className="rounded-[24px] border border-[#eadbd3] bg-white p-6"><div className="text-sm tracking-[.18em] text-[#f2af27]">★★★★★</div><blockquote className="serif mt-4 text-xl font-bold leading-8">“{review.quote}”</blockquote><figcaption className="mt-5 text-xs"><span className="font-black">{review.name}</span><span className="ml-2 text-[#9297a4]">{review.detail}</span></figcaption></figure>)}</div><div className="mt-8 grid gap-3 rounded-[22px] bg-white p-5 text-xs font-black text-[#59627b] sm:grid-cols-2 lg:grid-cols-4">{[es ? "Vista previa antes de continuar" : "Pré-visualização antes de continuar", es ? "Personalizado por ti" : "Personalizado por ti", es ? "Preparado con cuidado" : "Preparado com cuidado", es ? "Hecho por encargo" : "Feito por encomenda"].map((item) => <span key={item} className="flex items-center gap-2"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-[#e8f5ed] text-[#24714b]"><Icon name="check" size={13} /></span>{item}</span>)}</div></div></section>

      <section className="bg-[#fff0e8] py-14 md:py-20"><div className="container"><div className="flex flex-col items-center justify-between gap-8 overflow-hidden rounded-[30px] bg-[#ee5264] px-7 py-11 text-center text-white sm:px-11 md:flex-row md:text-left"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-white/70">{es ? "UN REGALO QUE SOLO PUEDE SER SUYO" : "UM PRESENTE QUE SÓ PODE SER DELES"}</p><h2 className="serif mt-3 text-3xl font-bold sm:text-5xl">{es ? "Regálales algo verdaderamente suyo." : "Oferece algo verdadeiramente deles."}</h2><p className="mt-3 text-sm text-white/80">{es ? "Una foto favorita. Un mensaje especial. Un recuerdo que conservarán." : "Uma fotografia favorita. Uma mensagem especial. Uma memória para guardar."}</p></div><Link href="/templates" className="focus-ring inline-flex shrink-0 items-center gap-2 rounded-full bg-white px-6 py-3.5 text-sm font-black text-[#182443] transition hover:-translate-y-0.5">{es ? "Crear mi regalo personalizado" : "Criar o meu presente"}<Icon name="arrow" size={16} /></Link></div></div></section>
    </main>
    <SiteFooter />
  </>;
}

function SectionHeading({ eyebrow, title, body, dark = false }: { eyebrow: string; title: string; body?: string; dark?: boolean }) { return <div className="mx-auto max-w-[720px] text-center"><p className={`text-[10px] font-black uppercase tracking-[.2em] ${dark ? "text-[#f8c75e]" : "text-[#ee5264]"}`}>{eyebrow}</p><h2 className={`serif mt-3 text-4xl font-bold tracking-[-.04em] sm:text-5xl ${dark ? "text-white" : "text-[#182443]"}`}>{title}</h2>{body && <p className={`mx-auto mt-4 max-w-[580px] text-sm leading-6 ${dark ? "text-white/65" : "text-[#737b90]"}`}>{body}</p>}</div>; }
function Transformation({ before, after, label, birthdayCard = false }: { before: string; after: string; label: string; birthdayCard?: boolean }) { return <article className="rounded-[26px] border border-white/10 bg-white/[.06] p-4 sm:p-6"><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-3"><div className="aspect-square overflow-hidden rounded-2xl bg-white/10"><img src={before} alt="" className="h-full w-full object-cover" /></div><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#f8c75e] font-black text-[#182443]">→</span><div className="aspect-square overflow-hidden rounded-2xl bg-white">{birthdayCard ? <CardPreview templateId="template-3" message="Feliz cumpleaños" emoji="🎂" emojiElements={[]} photoDataUrl={after} frameId="balloon-frame" className="h-full w-full !aspect-auto" /> : <img src={after} alt="" className="h-full w-full object-cover" />}</div></div><h3 className="mt-5 text-center text-sm font-black">{label}</h3></article>; }
function GalleryTile({ image, label, className = "" }: { image: string; label: string; className?: string }) { return <figure className={`group relative min-h-[190px] overflow-hidden rounded-[22px] ${className}`}><img src={image} alt={label} className="absolute inset-0 h-full w-full object-cover object-center transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-[#182443]/75 via-transparent to-transparent" /><figcaption className="absolute bottom-4 left-4 text-sm font-black text-white">{label}</figcaption></figure>; }
