"use client";

import { ChangeEvent, useRef, useState } from "react";
import Link from "next/link";
import { useSelector } from "react-redux";
import { Icon } from "@/components/icons";
import { PageIntro, SiteFooter, SiteHeader } from "@/components/site";
import { RootState } from "@/lib/store";

function readPhoto(event: ChangeEvent<HTMLInputElement>, onRead: (value: string) => void) {
  const file = event.target.files?.[0];
  if (!file) return;
  const reader = new FileReader();
  reader.onload = () => onRead(String(reader.result));
  reader.readAsDataURL(file);
}

function UploadButton({ photo, onPhoto, es }: { photo: string | null; onPhoto: (value: string) => void; es: boolean }) {
  const inputRef = useRef<HTMLInputElement>(null);
  return <>
    <button type="button" onClick={() => inputRef.current?.click()} className="focus-ring mt-3 flex w-full items-center gap-3 rounded-2xl border border-dashed border-[#e7a59c] bg-white p-3 text-left transition hover:bg-[#fff0e8]"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#fff0e8] text-[#ee5264]"><Icon name="plus" size={18} /></span><span><span className="block text-sm font-black">{photo ? (es ? "Cambiar fotografía" : "Alterar fotografia") : (es ? "Subir una fotografía" : "Carregar uma fotografia")}</span><span className="mt-0.5 block text-xs text-[#7c8191]">JPG o PNG · {es ? "la vista previa se actualiza aquí" : "a pré-visualização atualiza aqui"}</span></span></button>
    <input ref={inputRef} type="file" accept="image/png,image/jpeg" className="hidden" onChange={(event) => readPhoto(event, onPhoto)} />
  </>;
}

function StudioShell({ eyebrow, title, body, controls, preview, price, es }: { eyebrow: string; title: string; body: string; controls: React.ReactNode; preview: React.ReactNode; price: string; es: boolean }) {
  return <><SiteHeader /><main className="bg-[#fffaf5] py-12 md:py-20"><div className="container"><PageIntro eyebrow={eyebrow} title={title} body={body} /><div className="mt-10 grid gap-7 lg:grid-cols-[.78fr_1.22fr] lg:items-start"><section className="order-2 rounded-[24px] border border-[#eadfd8] bg-white p-5 sm:p-7 lg:order-1"><div className="flex items-center justify-between border-b border-[#eadfd8] pb-5"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#ee5264]">{es ? "TUS OPCIONES" : "AS TUAS OPÇÕES"}</p><h2 className="mt-1 text-lg font-black">{es ? "Hazlo a tu manera" : "Faz à tua maneira"}</h2></div><span className="rounded-full bg-[#fff0e8] px-3 py-1.5 text-xs font-black text-[#ee5264]">{price}</span></div>{controls}<div className="mt-7 border-t border-[#eadfd8] pt-5"><button type="button" onClick={() => window.alert(es ? "Demo frontend: el pedido se conectará al backend más adelante." : "Demonstração frontend: a encomenda será ligada ao backend mais tarde.")} className="focus-ring flex w-full items-center justify-center gap-2 rounded-full bg-[#ee5264] px-5 py-3.5 text-sm font-black text-white transition hover:bg-[#d83d54]">{es ? "Continuar" : "Continuar"} <Icon name="arrow" size={16} /></button><p className="mt-3 text-center text-[11px] text-[#9297a4]">{es ? "Vista de demostración · no se realizará ningún pedido" : "Vista de demonstração · nenhuma encomenda será realizada"}</p></div></section><section className="order-1 rounded-[26px] bg-[#f5ece5] p-4 sm:p-8 lg:sticky lg:top-28 lg:order-2"><div className="mb-5 flex items-center justify-between"><span className="text-[10px] font-black uppercase tracking-[.18em] text-[#7b7180]">{es ? "VISTA PREVIA" : "PRÉ-VISUALIZAÇÃO"}</span><span className="flex items-center gap-1.5 text-[11px] font-bold text-[#59627b]"><Icon name="check" size={13} /> {es ? "Se actualiza al instante" : "Atualiza de imediato"}</span></div>{preview}</section></div><div className="mt-8 text-center"><Link href="/#categories" className="text-xs font-black text-[#737b90] underline underline-offset-4 hover:text-[#ee5264]">← {es ? "Volver a todos los productos" : "Voltar a todos os produtos"}</Link></div></div></main><SiteFooter /></>;
}

export function CalendarStudio() {
  const es = useSelector((state: RootState) => state.language.language) === "es";
  const [size, setSize] = useState<"A4" | "A5">("A4");
  const [dated, setDated] = useState(true);
  const [photo, setPhoto] = useState<string | null>(null);
  const months = es ? ["ENE", "FEB", "MAR", "ABR", "MAY", "JUN", "JUL", "AGO", "SEP", "OCT", "NOV", "DIC"] : ["JAN", "FEV", "MAR", "ABR", "MAI", "JUN", "JUL", "AGO", "SET", "OUT", "NOV", "DEZ"];
  const price = size === "A4" ? "18,90 €" : "16,90 €";
  const controls = <div className="mt-6 space-y-6"><div><p className="text-sm font-black">{es ? "Tamaño" : "Tamanho"}</p><div className="mt-3 grid grid-cols-2 gap-3">{(["A4", "A5"] as const).map((option) => <button key={option} type="button" onClick={() => setSize(option)} className={`focus-ring rounded-2xl border p-4 text-left transition ${size === option ? "border-[#ee5264] bg-[#fff0e8]" : "border-[#dfd3cc] hover:border-[#ee5264]"}`}><span className="flex items-center justify-between"><span className="text-base font-black">{option}</span><span className={`h-4 w-4 rounded-full border ${size === option ? "border-[5px] border-[#ee5264]" : "border-[#b7b0ac]"}`} /></span><span className="mt-2 block text-xs text-[#737b90]">{option === "A4" ? "21 × 29,7 cm" : "14,8 × 21 cm"}</span></button>)}</div></div><div><p className="text-sm font-black">{es ? "Tipo de calendario" : "Tipo de calendário"}</p><button type="button" onClick={() => setDated(!dated)} className={`focus-ring mt-3 flex w-full items-center gap-4 rounded-2xl border p-4 text-left transition ${dated ? "border-[#ee5264] bg-[#fff0e8]" : "border-[#dfd3cc]"}`}><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${dated ? "bg-[#ee5264] text-white" : "bg-[#f4eee9]"}`}><Icon name="check" size={18} /></span><span className="flex-1"><span className="block text-sm font-black">{es ? "Con fechas" : "Com datas"}</span><span className="mt-1 block text-xs leading-5 text-[#737b90]">{es ? "12 meses listos para empezar en enero." : "12 meses prontos para começar em janeiro."}</span></span></button></div><div><p className="text-sm font-black">{es ? "Foto de portada" : "Fotografia de capa"}</p><UploadButton photo={photo} onPhoto={setPhoto} es={es} /></div></div>;
  const preview = <div className="mx-auto max-w-[560px]"><div className={`mx-auto overflow-hidden bg-white shadow-2xl shadow-[#8a564c]/15 transition-all ${size === "A5" ? "w-[70%] rounded-[14px]" : "w-full rounded-[18px]"}`}><div className="flex h-5 items-center justify-center gap-3 bg-[#182443]">{Array.from({ length: 13 }).map((_, index) => <span key={index} className="h-2.5 w-1 rounded-full bg-white/70" />)}</div><img src={photo || "/images/calendar-product.png"} alt={es ? "Vista previa del calendario" : "Pré-visualização do calendário"} className="aspect-[1.65/1] w-full object-cover" /><div className="p-4 sm:p-6"><div className="flex items-end justify-between border-b border-[#182443] pb-3"><h3 className="serif text-3xl font-bold">{dated ? (es ? "ENERO" : "JANEIRO") : (es ? "TU MES" : "O TEU MÊS")}</h3><span className="text-[10px] font-black">2027</span></div><div className="mt-3 grid grid-cols-7 gap-px bg-[#eadfd8]">{Array.from({ length: 35 }).map((_, index) => <span key={index} className="flex aspect-square items-start justify-end bg-white p-1 text-[7px] text-[#59627b]">{dated && index > 2 && index < 34 ? index - 2 : ""}</span>)}</div></div></div><div className="mt-4 flex flex-wrap justify-center gap-1.5">{months.map((month, index) => <span key={month} className={`rounded-full px-2.5 py-1 text-[9px] font-black ${index === 0 ? "bg-[#182443] text-white" : "bg-white text-[#9297a4]"}`}>{month}</span>)}</div></div>;
  return <StudioShell eyebrow={es ? "CALENDARIOS PERSONALIZADOS" : "CALENDÁRIOS PERSONALIZADOS"} title={es ? "Un año lleno de los tuyos" : "Um ano cheio dos teus"} body={es ? "Elige A4 o A5, añade tu foto y revisa cómo quedará tu calendario con fechas." : "Escolhe A4 ou A5, adiciona a tua fotografia e vê como ficará o calendário com datas."} controls={controls} preview={preview} price={price} es={es} />;
}

export function WallArtStudio() {
  const es = useSelector((state: RootState) => state.language.language) === "es";
  const products = [{ id: "single", name: es ? "Marco protagonista" : "Moldura protagonista", detail: "30 × 40 cm", price: "29,90 €" }, { id: "gallery", name: es ? "Galería de tres" : "Galeria de três", detail: "1 grande + 2 medianos", price: "39,90 €" }, { id: "pair", name: es ? "Dúo de láminas" : "Duo de impressões", detail: "2 × 21 × 30 cm", price: "32,90 €" }] as const;
  const [selected, setSelected] = useState<(typeof products)[number]["id"]>("gallery");
  const [frame, setFrame] = useState<"natural" | "white" | "navy">("natural");
  const [photo, setPhoto] = useState<string | null>(null);
  const product = products.find((item) => item.id === selected)!;
  const frameColors = { natural: "#caa57b", white: "#f8f5ef", navy: "#182443" };
  const controls = <div className="mt-6 space-y-6"><div><p className="text-sm font-black">{es ? "Productos seleccionados" : "Produtos selecionados"}</p><div className="mt-3 grid gap-2">{products.map((item) => <button key={item.id} type="button" onClick={() => setSelected(item.id)} className={`focus-ring flex items-center justify-between rounded-2xl border p-4 text-left transition ${selected === item.id ? "border-[#ee5264] bg-[#fff0e8]" : "border-[#dfd3cc] hover:border-[#ee5264]"}`}><span><span className="block text-sm font-black">{item.name}</span><span className="mt-1 block text-xs text-[#737b90]">{item.detail}</span></span><span className="text-xs font-black text-[#ee5264]">{item.price}</span></button>)}</div></div><div><p className="text-sm font-black">{es ? "Acabado" : "Acabamento"}</p><div className="mt-3 flex gap-3">{(["natural", "white", "navy"] as const).map((color) => <button key={color} type="button" onClick={() => setFrame(color)} aria-label={color} className={`focus-ring h-11 w-11 rounded-full border-4 shadow-sm ${frame === color ? "border-[#ee5264]" : "border-white"}`} style={{ backgroundColor: frameColors[color] }} />)}</div></div><div><p className="text-sm font-black">{es ? "Tu fotografía" : "A tua fotografia"}</p><UploadButton photo={photo} onPhoto={setPhoto} es={es} /></div></div>;
  const picture = <img src={photo || "/images/wall-art-product.png"} alt="" className="h-full w-full object-cover" />;
  const preview = <div className="relative aspect-[4/3] overflow-hidden rounded-[20px] bg-[#efe7dc] p-7 sm:p-12"><div className="absolute bottom-0 left-0 right-0 h-[20%] bg-[#d8b98e]" />{selected === "single" ? <div className="relative mx-auto h-[82%] w-[48%] p-2 shadow-2xl" style={{ backgroundColor: frameColors[frame] }}>{picture}</div> : selected === "pair" ? <div className="relative mx-auto grid h-[78%] w-[75%] grid-cols-2 gap-5">{[0, 1].map((item) => <div key={item} className="p-2 shadow-2xl" style={{ backgroundColor: frameColors[frame] }}>{picture}</div>)}</div> : <div className="relative mx-auto grid h-[78%] w-[82%] grid-cols-2 grid-rows-2 gap-4"><div className="row-span-2 p-2 shadow-2xl" style={{ backgroundColor: frameColors[frame] }}>{picture}</div>{[0, 1].map((item) => <div key={item} className="p-2 shadow-2xl" style={{ backgroundColor: frameColors[frame] }}>{picture}</div>)}</div>}</div>;
  return <StudioShell eyebrow={es ? "ARTE DE PARED" : "ARTE DE PAREDE"} title={es ? "Tus recuerdos, bien enmarcados" : "As tuas memórias, bem emolduradas"} body={es ? "Una colección pequeña y cuidada: elige una composición, un acabado y tu foto favorita." : "Uma coleção pequena e cuidada: escolhe uma composição, um acabamento e a tua fotografia favorita."} controls={controls} preview={preview} price={product.price} es={es} />;
}

export function MagnetsStudio() {
  const es = useSelector((state: RootState) => state.language.language) === "es";
  const [quantity, setQuantity] = useState<4 | 9>(9);
  const [shape, setShape] = useState<"square" | "round">("square");
  const [photo, setPhoto] = useState<string | null>(null);
  const price = quantity === 4 ? "9,90 €" : "14,90 €";
  const controls = <div className="mt-6 space-y-6"><div><p className="text-sm font-black">{es ? "Tamaño del pack" : "Tamanho do conjunto"}</p><div className="mt-3 grid grid-cols-2 gap-3">{([4, 9] as const).map((amount) => <button key={amount} type="button" onClick={() => setQuantity(amount)} className={`focus-ring rounded-2xl border p-4 text-left transition ${quantity === amount ? "border-[#ee5264] bg-[#fff0e8]" : "border-[#dfd3cc] hover:border-[#ee5264]"}`}><span className="flex items-center justify-between"><span className="text-lg font-black">{amount}</span><span className="text-xs font-black text-[#ee5264]">{amount === 4 ? "9,90 €" : "14,90 €"}</span></span><span className="mt-2 block text-xs text-[#737b90]">{es ? "imanes de 6 × 6 cm" : "ímanes de 6 × 6 cm"}</span></button>)}</div></div><div><p className="text-sm font-black">{es ? "Forma" : "Forma"}</p><div className="mt-3 grid grid-cols-2 gap-3">{(["square", "round"] as const).map((option) => <button key={option} type="button" onClick={() => setShape(option)} className={`focus-ring flex items-center gap-3 rounded-2xl border p-3 text-sm font-black transition ${shape === option ? "border-[#ee5264] bg-[#fff0e8]" : "border-[#dfd3cc]"}`}><span className={`h-7 w-7 bg-[#182443] ${option === "round" ? "rounded-full" : "rounded-md"}`} />{option === "square" ? (es ? "Cuadrado" : "Quadrado") : (es ? "Redondo" : "Redondo")}</button>)}</div></div><div><p className="text-sm font-black">{es ? "Primera fotografía" : "Primeira fotografia"}</p><UploadButton photo={photo} onPhoto={setPhoto} es={es} /><p className="mt-2 text-[11px] leading-5 text-[#9297a4]">{es ? "En el flujo final podrás añadir una foto distinta a cada imán." : "No fluxo final poderás adicionar uma fotografia diferente a cada íman."}</p></div></div>;
  const preview = <div className={`grid gap-3 rounded-[20px] bg-[#fdfaf5] p-5 shadow-inner sm:gap-4 sm:p-8 ${quantity === 4 ? "mx-auto max-w-[460px] grid-cols-2" : "grid-cols-3"}`}>{Array.from({ length: quantity }).map((_, index) => <div key={index} className={`aspect-square overflow-hidden border-[5px] border-white bg-white shadow-lg ${shape === "round" ? "rounded-full" : "rounded-xl"}`}><img src={index === 0 && photo ? photo : "/images/magnets-product.png"} alt={index === 0 ? (es ? "Vista previa del imán" : "Pré-visualização do íman") : ""} className="h-full w-full object-cover" style={{ objectPosition: `${18 + (index % 3) * 31}% ${18 + Math.floor(index / 3) * 31}%` }} /></div>)}</div>;
  return <StudioShell eyebrow={es ? "IMANES PERSONALIZADOS" : "ÍMANES PERSONALIZADOS"} title={es ? "Recuerdos que siempre tienes a la vista" : "Memórias sempre à vista"} body={es ? "Elige 4 o 9, cuadrados o redondos, y convierte cada foto en un pequeño detalle cotidiano." : "Escolhe 4 ou 9, quadrados ou redondos, e transforma cada fotografia num pequeno detalhe diário."} controls={controls} preview={preview} price={price} es={es} />;
}
