"use client";

import Link from "next/link";
import { ChangeEvent, useRef, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { CardPreview } from "@/components/card-preview";
import { Icon } from "@/components/icons";
import { PageIntro, SiteFooter, SiteHeader, Toast } from "@/components/site";
import { templates } from "@/lib/data";
import { RootState, setDelivery, setEmoji, setMessage, setPhoto, setPhotoPosition, setPhotoZoom, setRecipientMode, setSize, setTemplate } from "@/lib/store";

const cropPositions = [["left", "Izquierda"], ["center", "Centro"], ["right", "Derecha"], ["top", "Arriba"], ["bottom", "Abajo"]] as const;

export default function CustomizePage() {
  const dispatch = useDispatch();
  const cart = useSelector((state: RootState) => state.cart);
  const [toast, setToast] = useState("");
  const inputRef = useRef<HTMLInputElement>(null);
  const template = templates.find((item) => item.id === cart.card.templateId) || templates[0];
  const handlePhoto = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { dispatch(setPhoto(String(reader.result))); dispatch(setPhotoZoom(1)); dispatch(setPhotoPosition("center")); }; reader.readAsDataURL(file); };
  const reset = () => { dispatch(setMessage("Feliz vuelta al sol, Ana ✨")); dispatch(setEmoji("✨")); dispatch(setPhoto(null)); dispatch(setPhotoZoom(1)); dispatch(setPhotoPosition("center")); dispatch(setSize("A4")); };
  return <><SiteHeader active="Diseños" /><main className="bg-white"><div className="container pb-24 pt-14"><PageIntro eyebrow="TU TARJETA, TU HISTORIA" title="Personaliza tu diseño" body="Hazlo tuyo en un par de minutos. Puedes cambiarlo todo antes de pedir." /><div className="mt-14 grid gap-8 lg:grid-cols-[.78fr_1.22fr] lg:items-start">
    <section className="order-2 rounded-[24px] border border-[#eadfd8] bg-[#fffaf5] p-5 sm:p-7 lg:order-1" aria-label="Controles de personalización">
      <div className="flex items-center justify-between border-b border-[#eadfd8] pb-5"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#ee5264]">{template.eyebrow}</p><h2 className="mt-1 font-black">{template.name}</h2></div><button onClick={reset} className="text-xs font-bold text-[#7c8191] underline underline-offset-4 hover:text-[#ee5264]">Restablecer</button></div>
      <div className="mt-6"><p className="text-sm font-black">Elige un diseño</p><div className="mt-3 grid grid-cols-3 gap-2">{templates.map((item) => <button key={item.id} onClick={() => dispatch(setTemplate(item.id))} className={`focus-ring overflow-hidden rounded-xl border-2 bg-white text-left transition ${item.id === template.id ? "border-[#ee5264]" : "border-transparent"}`}><img src={item.image} alt={item.name} className="aspect-square w-full object-cover" /><span className="block truncate px-2 py-2 text-[10px] font-bold">{item.name}</span></button>)}</div></div>
      <label className="mt-6 block text-sm font-black">Tu mensaje<textarea value={cart.card.message} onChange={(event) => dispatch(setMessage(event.target.value))} rows={3} className="focus-ring mt-2 w-full resize-none rounded-2xl border border-[#dfd3cc] bg-white p-3 text-sm leading-6 text-[#182443] placeholder:text-[#adb1bd]" /></label>
      <div className="mt-5"><p className="text-sm font-black">Añade un emoji</p><div className="mt-2 flex gap-2">{["✨", "❤️", "🎉", "🌷", "😊"].map((item) => <button key={item} onClick={() => dispatch(setEmoji(item))} className={`focus-ring flex h-10 w-10 items-center justify-center rounded-xl border text-lg transition ${cart.card.emoji === item ? "border-[#ee5264] bg-[#fff0e8]" : "border-[#dfd3cc] bg-white hover:border-[#ee5264]"}`}>{item}</button>)}</div></div>
      <div className="mt-6"><p className="text-sm font-black">Tu foto</p><button onClick={() => inputRef.current?.click()} className="focus-ring mt-2 flex w-full items-center gap-3 rounded-2xl border border-dashed border-[#e7a59c] bg-white p-3 text-left transition hover:bg-[#fff0e8]"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#fff0e8] text-[#ee5264]"><Icon name="plus" size={18} /></span><span><span className="block text-sm font-black">{cart.card.photoDataUrl ? "Cambiar foto" : "Subir una foto"}</span><span className="mt-0.5 block text-xs text-[#7c8191]">JPG o PNG · hasta 10 MB</span></span></button><input ref={inputRef} onChange={handlePhoto} type="file" accept="image/png,image/jpeg" className="hidden" /></div>
      <div className={`mt-4 rounded-2xl border border-[#eadbd3] bg-white p-4 ${cart.card.photoDataUrl ? "" : "opacity-55"}`}><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-black">Ajusta tu foto</p><p className="mt-1 text-xs text-[#7c8191]">Mueve y acerca la imagen para encontrar el encuadre perfecto.</p></div><span className="rounded-full bg-[#fff0e8] px-2.5 py-1 text-[10px] font-black text-[#c94758]">{cart.card.photoDataUrl ? "Editable" : "Sube una foto"}</span></div><label className="mt-4 block text-xs font-black">Zoom <input aria-label="Zoom de la foto" type="range" min="1" max="1.5" step="0.05" value={cart.card.photoZoom} onChange={(event) => dispatch(setPhotoZoom(Number(event.target.value)))} disabled={!cart.card.photoDataUrl} className="mt-3 w-full accent-[#ee5264]" /><span className="mt-1 flex justify-between text-[10px] font-normal text-[#9297a4]"><span>Más imagen</span><span>{Math.round(cart.card.photoZoom * 100)}%</span><span>Más detalle</span></span></label><div className="mt-4"><p className="text-xs font-black">Posición</p><div className="mt-2 grid grid-cols-5 gap-1.5">{cropPositions.map(([value, label]) => <button key={value} title={label} disabled={!cart.card.photoDataUrl} onClick={() => dispatch(setPhotoPosition(value))} className={`focus-ring rounded-xl border px-1 py-2 text-[10px] font-bold transition disabled:cursor-not-allowed ${cart.card.photoPosition === value ? "border-[#ee5264] bg-[#fff0e8] text-[#c94758]" : "border-[#dfd3cc] hover:border-[#ee5264]"}`}>{label}</button>)}</div></div></div>
      <div className="mt-6"><p className="text-sm font-black">Tamaño</p><div className="mt-2 grid grid-cols-2 gap-2">{(["A4", "A3"] as const).map((option) => <button key={option} onClick={() => dispatch(setSize(option))} className={`focus-ring rounded-2xl border p-3 text-left transition ${cart.card.size === option ? "border-[#ee5264] bg-[#fff0e8]" : "border-[#dfd3cc] bg-white hover:border-[#ee5264]"}`}><span className="block text-sm font-black">{option}</span><span className="mt-1 block text-[11px] text-[#7c8191]">{option === "A4" ? "21 × 29,7 cm" : "29,7 × 42 cm"}</span></button>)}</div></div>
      <div className="mt-6"><p className="text-sm font-black">¿Dónde lo enviamos?</p><div className="mt-2 grid gap-2">{([["recipient", "Directamente a quien lo recibe", "Nosotros lo preparamos y lo entregamos por ti."], ["customer", "A mi dirección", "Recíbelo en casa, listo para entregar."]] as const).map(([value, title, body]) => <button key={value} onClick={() => dispatch(setRecipientMode(value))} className={`focus-ring rounded-2xl border p-3 text-left transition ${cart.card.recipientMode === value ? "border-[#ee5264] bg-[#fff0e8]" : "border-[#dfd3cc] bg-white hover:border-[#ee5264]"}`}><span className="flex items-center gap-2 text-sm font-black"><span className={`h-3 w-3 rounded-full border ${cart.card.recipientMode === value ? "border-[4px] border-[#ee5264]" : "border-[#b7b0ac]"}`} />{title}</span><span className="mt-1 block pl-5 text-xs text-[#7c8191]">{body}</span></button>)}</div></div>
      <div className="mt-6"><p className="text-sm font-black">Entrega</p><div className="mt-2 grid grid-cols-2 gap-2">{([["standard", "Estándar", "3–5 días", "Gratis"], ["express", "Express", "1–2 días", "+ 3,90 €"]] as const).map(([value, title, estimate, price]) => <button key={value} onClick={() => dispatch(setDelivery(value))} className={`focus-ring rounded-2xl border p-3 text-left transition ${cart.card.delivery === value ? "border-[#ee5264] bg-[#fff0e8]" : "border-[#dfd3cc] bg-white hover:border-[#ee5264]"}`}><span className="block text-sm font-black">{title}</span><span className="mt-1 block text-[11px] text-[#7c8191]">{estimate} · {price}</span></button>)}</div></div>
    </section>
    <section className="order-1 rounded-[26px] bg-[#f8efe8] p-5 sm:p-10 lg:order-2"><div className="mb-5 flex items-center justify-between"><span className="text-[10px] font-black uppercase tracking-[.18em] text-[#7b7180]">Vista previa</span><span className="rounded-full bg-white px-3 py-1.5 text-[11px] font-black text-[#182443]">{cart.card.size} · {template.eyebrow}</span></div><div className="mx-auto max-w-[640px] rounded-[18px] bg-white p-3 shadow-xl shadow-[#8a564c]/10 sm:p-5"><CardPreview templateId={template.id} message={cart.card.message} emoji={cart.card.emoji} photoDataUrl={cart.card.photoDataUrl} photoZoom={cart.card.photoZoom} photoPosition={cart.card.photoPosition} size={cart.card.size} /></div><p className="mx-auto mt-4 max-w-[640px] text-center text-xs text-[#7b7180]">Así se verá tu tarjeta impresa en {cart.card.size}. Puedes volver atrás y ajustar cualquier detalle.</p><div className="mx-auto mt-6 flex max-w-[640px] flex-col gap-3 sm:flex-row"><Link href="/addons" className="focus-ring inline-flex flex-1 items-center justify-center gap-3 rounded-full bg-[#ee5264] px-5 py-3.5 text-sm font-black text-white transition hover:bg-[#d83d54]">Continuar con extras <Icon name="arrow" size={17} /></Link><button onClick={() => setToast("Tu diseño se ha guardado en esta sesión")} className="focus-ring rounded-full border border-[#d9cbc4] bg-white px-5 py-3.5 text-sm font-black text-[#182443] transition hover:border-[#ee5264]">Guardar diseño</button></div></section>
  </div></div></main><SiteFooter />{toast && <Toast message={toast} onClose={() => setToast("")} />}</>;
}
