"use client";

import Link from "next/link";
import { ChangeEvent, useRef, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { Icon } from "@/components/icons";
import { PageIntro, Price, SiteFooter, SiteHeader, Toast } from "@/components/site";
import { ENVELOPE_TEXT_PRICE, STICKER_PRICES, stickerGallery, templates } from "@/lib/data";
import { RootState, setEnvelopeText, setEnvelopeTextAdded, setStickerImage, setStickerQuantity } from "@/lib/store";

export default function AddonsPage() {
  const dispatch = useDispatch();
  const cart = useSelector((state: RootState) => state.cart);
  const es = useSelector((state: RootState) => state.language.language) === "es";
  const [toast, setToast] = useState("");
  const fileRef = useRef<HTMLInputElement>(null);
  const template = templates.find((item) => item.id === cart.card.templateId) || templates[0];
  const readPhoto = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { dispatch(setStickerImage(String(reader.result))); setToast(es ? "Imagen del sticker guardada" : "Imagem do sticker guardada"); }; reader.readAsDataURL(file); };
  const toggleEnvelope = () => { if (!cart.envelopeTextAdded && !cart.envelopeText.trim()) { setToast(es ? "Escribe primero el texto del sobre" : "Escreve primeiro o texto do envelope"); return; } dispatch(setEnvelopeTextAdded(!cart.envelopeTextAdded)); setToast(cart.envelopeTextAdded ? (es ? "Texto eliminado" : "Texto removido") : (es ? "Texto añadido" : "Texto adicionado")); };

  return <><SiteHeader /><main className="bg-[#fffaf5] py-14 md:py-20"><div className="container"><PageIntro eyebrow={es ? "DETALLES OPCIONALES" : "DETALHES OPCIONAIS"} title={es ? "Completa el momento" : "Completa o momento"} body={es ? "Dos extras sencillos para hacer que abrir el sobre sea todavía más especial." : "Dois extras simples para tornar a abertura do envelope ainda mais especial."} /><div className="mx-auto mt-12 grid max-w-[980px] gap-6 lg:grid-cols-2">
    <section className="rounded-[26px] border border-[#eadbd3] bg-white p-5 sm:p-8"><div className="flex items-start justify-between gap-4"><div><span className="text-[10px] font-black tracking-[.18em] text-[#ee5264]">01 · {es ? "TU FOTO" : "A TUA FOTO"}</span><h2 className="mt-2 text-2xl font-black">Sticker personalizado</h2><p className="mt-2 text-sm leading-6 text-[#737b90]">{es ? "Un círculo de 7,62 cm con tu fotografía favorita." : "Um círculo de 7,62 cm com a tua fotografia favorita."}</p></div><div className="relative h-24 w-24 shrink-0 overflow-hidden rounded-full border-[5px] border-white bg-[#fff0e8] shadow-[0_0_0_2px_#f8c75e] sm:h-28 sm:w-28"><img src={cart.stickerImage || "/images/sticker-dog.jpg"} alt="Sticker" className="h-full w-full object-cover" /></div></div><div className="mt-7 grid grid-cols-4 gap-2">{([0, 1, 2, 3] as const).map((quantity) => <button key={quantity} onClick={() => dispatch(setStickerQuantity(quantity))} className={`focus-ring rounded-xl border py-3 text-sm font-black ${cart.stickerQuantity === quantity ? "border-[#ee5264] bg-[#fff0e8] text-[#ee5264]" : "border-[#dfd3cc]"}`}>{quantity === 0 ? (es ? "No" : "Não") : <><span className="block">{quantity}</span><span className="mt-1 block text-[10px] font-normal text-[#737b90]">{STICKER_PRICES[quantity].toFixed(2).replace(".", ",")} €</span></>}</button>)}</div><button onClick={() => fileRef.current?.click()} className="focus-ring mt-5 flex w-full items-center gap-3 rounded-2xl border border-dashed border-[#e7a59c] p-3 text-left hover:bg-[#fff0e8]"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#fff0e8] text-[#ee5264]"><Icon name="plus" size={18} /></span><span><span className="block text-sm font-black">{cart.stickerImage ? (es ? "Cambiar foto" : "Alterar fotografia") : (es ? "Subir tu foto" : "Carregar fotografia")}</span><span className="block text-xs text-[#7c8191]">JPG o PNG</span></span></button><input ref={fileRef} onChange={readPhoto} type="file" accept="image/png,image/jpeg" className="hidden" /><div className="mt-5 grid grid-cols-4 gap-2">{stickerGallery.map((item) => <img key={item.id} src={item.image} alt={item.label} className="aspect-square w-full rounded-xl object-cover" />)}</div></section>
    <section className="rounded-[26px] border border-[#eadbd3] bg-white p-5 sm:p-8"><span className="text-[10px] font-black tracking-[.18em] text-[#ee5264]">02 · {es ? "PRIMERA IMPRESIÓN" : "PRIMEIRA IMPRESSÃO"}</span><div className="mt-2 flex items-start justify-between gap-4"><div><h2 className="text-2xl font-black">{es ? "Texto en el sobre" : "Texto no envelope"}</h2><p className="mt-1 text-sm font-black text-[#ee5264]"><Price value={ENVELOPE_TEXT_PRICE} /></p></div><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#fff0e8] text-xl">✍️</span></div><p className="mt-4 text-sm leading-6 text-[#737b90]">{es ? "Añade una frase corta en el exterior. Será lo primero que vea quien lo reciba." : "Adiciona uma frase curta no exterior. Será a primeira coisa que a pessoa verá."}</p><div className="mt-6 rounded-2xl border border-[#e5d8d0] bg-[#fffaf5] p-5"><p className="serif min-h-14 border-b border-[#d8cbc4] pb-4 text-center text-lg font-bold italic">{cart.envelopeText || (es ? "Tu mensaje aparecerá aquí…" : "A tua mensagem aparecerá aqui…")}</p><textarea value={cart.envelopeText} onChange={(event) => dispatch(setEnvelopeText(event.target.value))} maxLength={80} rows={3} placeholder={es ? "Para alguien que hace especiales mis días" : "Para alguém que torna os meus dias especiais"} className="focus-ring mt-4 w-full resize-none rounded-xl border border-[#dfd3cc] bg-white p-3 text-sm" /><div className="mt-3 flex items-center justify-between gap-3"><span className="text-[10px] text-[#9297a4]">{cart.envelopeText.length}/80</span><button onClick={toggleEnvelope} className={`focus-ring rounded-full px-4 py-2.5 text-xs font-black ${cart.envelopeTextAdded ? "border border-[#ee5264] text-[#ee5264]" : "bg-[#182443] text-white"}`}>{cart.envelopeTextAdded ? (es ? "Eliminar" : "Remover") : (es ? "Añadir" : "Adicionar")}</button></div></div></section>
  </div><div className="mx-auto mt-7 flex max-w-[980px] flex-col items-center justify-between gap-4 rounded-2xl bg-[#182443] p-5 text-white sm:flex-row sm:px-7"><div><p className="text-sm font-black">{es ? "Tu tarjeta está lista." : "O teu cartão está pronto."}</p><p className="mt-1 text-xs text-white/60">{template.eyebrow} · {es ? "Puedes revisar todo antes de pagar." : "Podes rever tudo antes de pagar."}</p></div><Link href="/cart" className="focus-ring inline-flex items-center gap-2 rounded-full bg-[#ee5264] px-5 py-3 text-sm font-black">{es ? "Ver mi selección" : "Ver a minha seleção"} <Icon name="arrow" size={16} /></Link></div></div></main><SiteFooter />{toast && <Toast message={toast} onClose={() => setToast("")} />}</>;
}
