"use client";

import { useState } from "react";
import { AdminPageHeader, AdminShell } from "@/components/admin";
import { StatusBadge, Toast } from "@/components/site";
import { useMockDb } from "@/lib/mock-store";

export default function AdminCustomersPage() {
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<string | null>(null);
  const [toast, setToast] = useState("");
  const db = useMockDb();
  const customers = db.users.map((user) => ({ name: user.name, email: user.email, orders: db.orders.filter((order) => order.userId === user.id || order.email === user.email).length, last: db.orders.find((order) => order.userId === user.id || order.email === user.email)?.date || "—", consent: true })).filter((customer) => `${customer.name} ${customer.email}`.toLowerCase().includes(query.toLowerCase()));
  const customer = customers.find((item) => item.email === selected);
  return <AdminShell><AdminPageHeader eyebrow="RELATIONSHIPS" title="Customers" body="Search customers, review their consent, and open a simple customer profile." action={<button onClick={() => setToast("Customer list export is ready for the backend connection")} className="rounded-full border border-[#dfe3eb] bg-white px-4 py-3 text-xs font-black">Export list</button>} />
    <section className="mt-8 overflow-hidden rounded-2xl border border-[#e4e7ee] bg-white"><div className="flex items-center justify-between gap-3 border-b border-[#e4e7ee] p-5"><p className="text-sm font-black">{customers.length} shown · 892 customers</p><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search customers" className="w-48 rounded-xl border border-[#dfd3cc] px-3 py-2 text-xs" /></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left"><thead><tr className="border-b border-[#e4e7ee] bg-[#fafbfc] text-[10px] uppercase tracking-[.14em] text-[#9297a4]"><th className="px-5 py-3 font-black">Customer</th><th className="px-5 py-3 font-black">Orders</th><th className="px-5 py-3 font-black">Last order</th><th className="px-5 py-3 font-black">Marketing consent</th><th className="px-5 py-3" /></tr></thead><tbody>{customers.map((item) => <tr key={item.email} className="border-b border-[#eef0f4] text-sm last:border-0"><td className="px-5 py-4"><p className="font-black">{item.name}</p><p className="mt-1 text-xs text-[#737b90]">{item.email}</p></td><td className="px-5 py-4 font-black">{item.orders}</td><td className="px-5 py-4 text-[#737b90]">{item.last}</td><td className="px-5 py-4"><StatusBadge tone={item.consent ? "green" : "slate"}>{item.consent ? "Opted in" : "Not opted in"}</StatusBadge></td><td className="px-5 py-4 text-right"><button onClick={() => setSelected(item.email)} className="text-xs font-black text-[#ee5264]">View</button></td></tr>)}</tbody></table></div></section>
    {customer && <div className="fixed inset-0 z-50"><button className="absolute inset-0 bg-[#182443]/25" onClick={() => setSelected(null)} aria-label="Close customer profile" /><aside className="absolute bottom-0 right-0 top-0 w-full max-w-[410px] bg-white p-6 shadow-2xl sm:p-8"><button onClick={() => setSelected(null)} className="float-right text-xs font-black text-[#737b90]">Close</button><p className="pt-8 text-[10px] font-black tracking-widest text-[#ee5264]">CUSTOMER PROFILE</p><h2 className="mt-2 text-2xl font-black">{customer.name}</h2><p className="mt-2 text-sm text-[#737b90]">{customer.email}</p><dl className="mt-9 divide-y divide-[#eef0f4]"><div className="flex justify-between py-4"><dt className="text-sm text-[#737b90]">Orders</dt><dd className="text-sm font-black">{customer.orders}</dd></div><div className="flex justify-between py-4"><dt className="text-sm text-[#737b90]">Last order</dt><dd className="text-sm font-black">{customer.last}</dd></div><div className="flex justify-between py-4"><dt className="text-sm text-[#737b90]">Marketing</dt><dd><StatusBadge tone={customer.consent ? "green" : "slate"}>{customer.consent ? "Opted in" : "Not opted in"}</StatusBadge></dd></div></dl></aside></div>}{toast && <Toast message={toast} onClose={() => setToast("")} />}
  </AdminShell>;
}
